services:
  client:
    build:
      context: ./client
      dockerfile: dockerfile
    ports:
      - 9080:80
    depends_on:
      - server
    restart: unless-stopped

  server:
    build:
      context: ./server
      dockerfile: dockerfile
    expose:
      - 5000
    restart: unless-stopped
